name: CI / CD

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[test]"

    - name: Run tests with coverage
      run: |
        pytest --maxfail=1 --disable-warnings --cov=napari_pitcount_cfim
