name: Build & Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade build twine

      - name: Build distributions
        run: |
          python -m build   # produces dist/*.whl and dist/*.tar.gz

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release
        with:
          # store a PyPI API token in your repo secrets under PYPI_API_TOKEN
          password: ${{ secrets.PYPI_TOKEN }}
